
package ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Operation", targetNamespace = "http://ws/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Operation {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addtion", targetNamespace = "http://ws/", className = "ws.Addtion")
    @ResponseWrapper(localName = "addtionResponse", targetNamespace = "http://ws/", className = "ws.AddtionResponse")
    @Action(input = "http://ws/Operation/addtionRequest", output = "http://ws/Operation/addtionResponse")
    public int addtion(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "soustration", targetNamespace = "http://ws/", className = "ws.Soustration")
    @ResponseWrapper(localName = "soustrationResponse", targetNamespace = "http://ws/", className = "ws.SoustrationResponse")
    @Action(input = "http://ws/Operation/soustrationRequest", output = "http://ws/Operation/soustrationResponse")
    public int soustration(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "multiplication", targetNamespace = "http://ws/", className = "ws.Multiplication")
    @ResponseWrapper(localName = "multiplicationResponse", targetNamespace = "http://ws/", className = "ws.MultiplicationResponse")
    @Action(input = "http://ws/Operation/multiplicationRequest", output = "http://ws/Operation/multiplicationResponse")
    public int multiplication(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

}
